// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublicLibrary.Data.Models;

#nullable disable

namespace PublicLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251216160630_ManyToManyAdded")]
    partial class ManyToManyAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyBook.Data.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("MyBook.Data.Models.Author_Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .IsUnique();

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("Author_Book");
                });

            modelBuilder.Entity("MyBook.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            CoverUrl = "https://example.com/greatgatsby.jpg",
                            DateAdded = new DateTime(1999, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRead = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A novel written by American author F. Scott Fitzgerald.",
                            Genre = "Classic",
                            IsRead = true,
                            Rate = 5,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            CoverUrl = "https://example.com/tokillamockingbird.jpg",
                            DateAdded = new DateTime(1980, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A novel by Harper Lee published in 1960.",
                            Genre = "Classic",
                            IsRead = false,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            CoverUrl = "https://example.com/1984.jpg",
                            DateAdded = new DateTime(1977, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A dystopian social science fiction novel and cautionary tale by the English writer George Orwell.",
                            Genre = "Dystopian",
                            IsRead = false,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            CoverUrl = "https://example.com/prideandprejudice.jpg",
                            DateAdded = new DateTime(1965, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A romantic novel of manners written by Jane Austen.",
                            Genre = "Romance",
                            IsRead = false,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 5,
                            Author = "J. R. R. Tolkien",
                            CoverUrl = "https://example.com/thehobbit.jpg",
                            DateAdded = new DateTime(1999, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A children's fantasy novel by English author J. R. R. Tolkien.",
                            Genre = "Fantasy",
                            IsRead = false,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Naguib Mahfouz",
                            CoverUrl = "https://example.com/benelqasreen.jpg",
                            DateAdded = new DateTime(1965, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A novel written by the famous egypt author Naguib Mahfouz.",
                            Genre = "Classic",
                            IsRead = true,
                            Title = "Ben Elqasreen"
                        });
                });

            modelBuilder.Entity("MyBook.Data.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publisher");
                });

            modelBuilder.Entity("MyBook.Data.Models.Author_Book", b =>
                {
                    b.HasOne("MyBook.Data.Models.Author", "author")
                        .WithOne("Author_Book")
                        .HasForeignKey("MyBook.Data.Models.Author_Book", "AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyBook.Data.Models.Book", "book")
                        .WithOne("Author_Book")
                        .HasForeignKey("MyBook.Data.Models.Author_Book", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("author");

                    b.Navigation("book");
                });

            modelBuilder.Entity("MyBook.Data.Models.Book", b =>
                {
                    b.HasOne("MyBook.Data.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("MyBook.Data.Models.Author", b =>
                {
                    b.Navigation("Author_Book");
                });

            modelBuilder.Entity("MyBook.Data.Models.Book", b =>
                {
                    b.Navigation("Author_Book");
                });

            modelBuilder.Entity("MyBook.Data.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
